In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [14]:
df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
df_binary = df[df['Species'].isin(['Iris-versicolor', 'Iris-virginica'])].copy()

In [22]:
X_binary = df_binary[['SepalLengthCm', 'SepalWidthCm']]

y_binary = df_binary['Species'].map({'Iris-versicolor': 0, 'Iris-virginica': 1})

In [23]:
X_bin_train, X_bin_test, y_bin_train, y_bin_test = train_test_split(
    X_binary, y_binary, test_size=0.2, random_state=42, stratify=y_binary
) 

X_binary.head()

    SepalLengthCm  SepalWidthCm
50            7.0           3.2
51            6.4           3.2
52            6.9           3.1
53            5.5           2.3
54            6.5           2.8

In [24]:
y_binary.head()

50    0
51    0
52    0
53    0
54    0
Name: Species, dtype: int64

In [31]:
binary_model = LogisticRegression()
binary_model.fit(X_bin_train, y_bin_train)

bin_test_preds = binary_model.predict(X_bin_test)
bin_accuracy = accuracy_score(y_bin_test, bin_test_preds)
print(f"최종 테스트 정확도: {bin_accuracy}:.4f")


kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_score = cross_val_score(multi_model, X_bin_train, y_bin_train, cv=kf)

print("\n[다중 분류 5-Fold 교차 검증]")
print("각 폴드별 정확도 수치:", cv_score)
print("평균 검증 정확도:", cv_score.mean())

multi_model.fit(X_bin_train, y_bin_train)

multi_test_preds = multi_model.predict(X_bin_test)
multi_accuracy = accuracy_score(y_bin_test, multi_test_preds)
print(f"다중 분류 최종 테스트 정확도: {multi_accuracy:.4f}")

최종 테스트 정확도: 0.7:.4f

[다중 분류 5-Fold 교차 검증]
각 폴드별 정확도 수치: [0.6875 0.625  0.6875 0.75   0.6875]
평균 검증 정확도: 0.6875
다중 분류 최종 테스트 정확도: 0.7000

In [30]:
X_multi = df[['SepalLengthCm', 'SepalWidthCm']]

y_multi = df['Species']

X_mul_train, X_mul_test, y_mul_train, y_mul_test = train_test_split(
    X_multi, y_multi, test_size=0.2, random_state=42, stratify=y_multi
)

X_multi.head(), y_multi[:5]

(   SepalLengthCm  SepalWidthCm
 0            5.1           3.5
 1            4.9           3.0
 2            4.7           3.2
 3            4.6           3.1
 4            5.0           3.6,
 0    Iris-setosa
 1    Iris-setosa
 2    Iris-setosa
 3    Iris-setosa
 4    Iris-setosa
 Name: Species, dtype: str)

In [35]:
kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(multi_model, X_mul_train, y_mul_train, cv=kf)

print("\n[다중 분류 5-Fold 교차 검증]")
print("각 폴드별 정확도 수치:", cv_scores)
print("평균 검증 정확도:", cv_scores.mean())

multi_model.fit(X_mul_train, y_mul_train)

multi_test_preds = multi_model.predict(X_mul_test)
multi_accuracy = accuracy_score(y_mul_test, multi_test_preds)
print(f"다중 분류 최종 테스트 정확도: {multi_accuracy:.4f}")

[다중 분류 5-Fold 교차 검증]
각 폴드별 정확도 수치: [0.79166667 0.79166667 0.875      0.70833333 0.875     ]
평균 검증 정확도: 0.8083333333333332
다중 분류 최종 테스트 정확도: 0.7333

In [33]:
df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa